export const URL = 'http://localhost:4444/';
// export const xbtusd = '?symbol=XBTUSD';
// export const ethusd = '?symbol=ETHUSD';
// export const bchh19 = '?symbol=BCHH19';
// export const xrph19 = '?symbol=XRPH19';
// export const adah19 = '?symbol=ADAH19';
// export const ltch19 = '?symbol=LTCH19';
// export const trxh19 = '?symbol=TRXH19';
// export const eosh19 = '?symbol=EOSH19';
export const ALL_INSTRUMENTS = ['XBTUSD','ETHUSD','BCHH19','XRPH19','ADAH19','LTCH19','TRXH19','EOSH19'];